@php($rate = $candidateTokenRate ?? null)
<div class="grid grid-cols-1 md:grid-cols-2 gap-6">
    <div><label class="block text-sm text-zinc-400 mb-2">Action Key</label><input name="action_key" value="{{ old('action_key', $rate?->action_key) }}" required class="w-full bg-zinc-800 border border-zinc-700 rounded-2xl px-4 py-3 text-white">@error('action_key')<p class="text-red-400 text-sm mt-2">{{ $message }}</p>@enderror</div>
    <div><label class="block text-sm text-zinc-400 mb-2">Label</label><input name="label" value="{{ old('label', $rate?->label) }}" required class="w-full bg-zinc-800 border border-zinc-700 rounded-2xl px-4 py-3 text-white">@error('label')<p class="text-red-400 text-sm mt-2">{{ $message }}</p>@enderror</div>
    <div><label class="block text-sm text-zinc-400 mb-2">Calculation Type</label><select name="calculation_type" class="w-full bg-zinc-800 border border-zinc-700 rounded-2xl px-4 py-3 text-white">@foreach(\App\Models\CandidateTokenRate::CALCULATION_TYPES as $type)<option value="{{ $type }}" {{ old('calculation_type', $rate?->calculation_type ?? 'fixed') === $type ? 'selected' : '' }}>{{ str_replace('_', ' ', ucfirst($type)) }}</option>@endforeach</select></div>
    <div><label class="block text-sm text-zinc-400 mb-2">Token Amount</label><input type="number" min="1" name="token_amount" value="{{ old('token_amount', $rate?->token_amount ?? 1) }}" required class="w-full bg-zinc-800 border border-zinc-700 rounded-2xl px-4 py-3 text-white">@error('token_amount')<p class="text-red-400 text-sm mt-2">{{ $message }}</p>@enderror</div>
    <div><label class="block text-sm text-zinc-400 mb-2">Sort Order</label><input type="number" min="0" name="sort_order" value="{{ old('sort_order', $rate?->sort_order ?? 0) }}" class="w-full bg-zinc-800 border border-zinc-700 rounded-2xl px-4 py-3 text-white"></div>
    <label class="flex items-center gap-3 mt-8"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" {{ old('is_active', $rate?->is_active ?? true) ? 'checked' : '' }}> Active</label>
</div>
<div class="mt-6"><label class="block text-sm text-zinc-400 mb-2">Public Explanation</label><textarea name="description" rows="4" class="w-full bg-zinc-800 border border-zinc-700 rounded-2xl px-4 py-3 text-white">{{ old('description', $rate?->description) }}</textarea></div>
