@extends('layouts.app')
@section('page_title','Parliamentary Data')
@section('content')
<div class="space-y-7">
 <div class="flex flex-wrap items-start justify-between gap-4"><div><h1 class="text-3xl font-semibold text-white"><i class="fas fa-landmark text-emerald-500 mr-3"></i>Parliamentary Data</h1><p class="mt-2 text-zinc-400">Review source members, confirm candidate links, and control public publication.</p></div>
 @if(!$importRun || $importRun->status==='failed')<form method="POST" action="{{ route('parliament-members.import') }}">@csrf<button class="rounded-2xl bg-emerald-600 px-5 py-3 font-semibold hover:bg-emerald-700"><i class="fas fa-cloud-arrow-down mr-2"></i>{{ $importRun ? 'Retry Directory Import' : 'Run One-time Import' }}</button></form>@else<div class="rounded-2xl border border-zinc-700 bg-zinc-900 px-5 py-3 text-sm"><span class="text-zinc-500">Directory import</span><strong class="ml-2 uppercase text-emerald-400">{{ $importRun->status }}</strong></div>@endif</div>
 @if(session('success'))<div class="rounded-2xl border border-emerald-500/30 bg-emerald-500/10 p-4 text-emerald-100">{{ session('success') }}</div>@endif
 @if($errors->any())<div class="rounded-2xl border border-red-500/30 bg-red-500/10 p-4 text-red-100"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
 <div class="grid grid-cols-2 gap-3 md:grid-cols-4 xl:grid-cols-7">@foreach($counts as $label=>$count)<div class="rounded-2xl border border-zinc-800 bg-zinc-900 p-4"><div class="text-xs uppercase tracking-wider text-zinc-500">{{ str_replace('_',' ',$label) }}</div><div class="mt-1 text-2xl font-bold text-white">{{ number_format($count) }}</div></div>@endforeach</div>
 <form method="GET" class="grid gap-3 rounded-3xl border border-zinc-800 bg-zinc-900 p-5 md:grid-cols-3 xl:grid-cols-6">
  <input name="search" value="{{ request('search') }}" placeholder="Member or constituency" class="rounded-xl border border-zinc-700 bg-zinc-800 px-4 py-3 text-white">
  <select name="house" class="rounded-xl border border-zinc-700 bg-zinc-800 px-4 py-3 text-white"><option value="">All houses</option>@foreach($houses as $house)<option value="{{ $house }}" @selected(request('house')===$house)>{{ ucfirst($house) }}</option>@endforeach</select>
  <select name="match_status" class="rounded-xl border border-zinc-700 bg-zinc-800 px-4 py-3 text-white"><option value="">All matches</option>@foreach(['unmatched','ambiguous','automatic','manual'] as $state)<option value="{{ $state }}" @selected(request('match_status')===$state)>{{ ucfirst($state) }}</option>@endforeach</select>
  <select name="detail_status" class="rounded-xl border border-zinc-700 bg-zinc-800 px-4 py-3 text-white"><option value="">All detail states</option>@foreach(['missing','fetching','failed','complete'] as $state)<option value="{{ $state }}" @selected(request('detail_status')===$state)>{{ ucfirst($state) }}</option>@endforeach</select>
  <select name="publication" class="rounded-xl border border-zinc-700 bg-zinc-800 px-4 py-3 text-white"><option value="">All publication states</option><option value="published" @selected(request('publication')==='published')>Published</option><option value="unpublished" @selected(request('publication')==='unpublished')>Unpublished</option></select>
  <button class="rounded-xl bg-zinc-700 px-4 py-3 font-semibold hover:bg-zinc-600">Filter</button>
 </form>
 <div class="space-y-4">@forelse($members as $member)
  <article class="rounded-3xl border border-zinc-800 bg-zinc-900 p-5">
   <div class="grid gap-5 xl:grid-cols-[1.2fr_1fr_auto]">
    <div><div class="flex flex-wrap items-center gap-2"><h2 class="text-xl font-semibold text-white">{{ $member->source_name }}</h2><span class="rounded-full bg-zinc-800 px-3 py-1 text-xs uppercase text-zinc-400">{{ $member->house ?: 'Unknown house' }}</span><span class="rounded-full px-3 py-1 text-xs uppercase {{ $member->detail_status==='complete'?'bg-emerald-500/15 text-emerald-300':($member->detail_status==='failed'?'bg-red-500/15 text-red-300':'bg-amber-500/15 text-amber-300') }}">{{ $member->detail_status }}</span></div><p class="mt-2 text-sm text-zinc-400">{{ collect([$member->role,$member->constituency,$member->party])->filter()->implode(' / ') }}</p><p class="mt-2 text-xs text-zinc-600">Source slug: {{ $member->external_slug }}</p>
     <details class="mt-4"><summary class="cursor-pointer text-sm font-semibold text-emerald-400">Preview imported details</summary><div class="mt-3 grid gap-3 rounded-2xl bg-zinc-950 p-4 text-sm text-zinc-300"><p>{{ $member->biography ?: 'No biography supplied.' }}</p><div><strong>Committees:</strong> {{ $member->committees->pluck('name')->implode('; ') ?: 'None supplied' }}</div><div><strong>Activities:</strong> {{ $member->activities->count() }}</div></div></details>
    </div>
    <div><div class="mb-2 text-xs font-semibold uppercase tracking-wider text-zinc-500">Candidate link</div><form method="POST" action="{{ route('parliament-members.link',$member) }}" class="space-y-2" data-member-link-form>@csrf @method('PATCH')<input type="hidden" name="candidate_id" value="{{ $member->candidate_id }}" data-candidate-id><div class="relative"><input type="search" value="{{ $member->candidate?->name }}" placeholder="Search candidate name" autocomplete="off" class="w-full rounded-xl border border-zinc-700 bg-zinc-800 px-4 py-3 text-white" data-candidate-search><div class="absolute z-20 mt-1 hidden w-full rounded-xl border border-zinc-700 bg-zinc-950 p-2 shadow-xl" data-candidate-results></div></div><div class="flex gap-2"><button class="rounded-xl bg-emerald-700 px-4 py-2 text-sm font-semibold">Save link</button><button type="button" class="rounded-xl border border-zinc-700 px-4 py-2 text-sm" data-clear-candidate>Unlink</button></div></form><p class="mt-2 text-xs text-zinc-500">Match: {{ $member->match_method ?: 'unmatched' }}@if($member->matched_token_count) ({{ $member->matched_token_count }} tokens)@endif</p></div>
    <div class="flex min-w-40 flex-col gap-2">@if($member->detail_status!=='complete')<form method="POST" action="{{ route('parliament-members.retry',$member) }}">@csrf<button class="w-full rounded-xl border border-amber-500/30 px-4 py-2 text-sm text-amber-300">Retry details</button></form>@endif<form method="POST" action="{{ route('parliament-members.publish',$member) }}">@csrf @method('PATCH')<input type="hidden" name="is_published" value="{{ $member->is_published?0:1 }}"><button class="w-full rounded-xl px-4 py-2 text-sm font-semibold {{ $member->is_published?'bg-red-700':'bg-emerald-600' }}">{{ $member->is_published?'Unpublish':'Publish' }}</button></form></div>
   </div>
  </article>@empty<div class="rounded-3xl border border-zinc-800 bg-zinc-900 p-12 text-center text-zinc-500">No parliamentary members found.</div>@endforelse</div>
 {{ $members->links() }}
</div>
@endsection
@push('scripts')<script>
document.querySelectorAll('[data-member-link-form]').forEach(function(form){const search=form.querySelector('[data-candidate-search]'),id=form.querySelector('[data-candidate-id]'),results=form.querySelector('[data-candidate-results]');let timer;search.addEventListener('input',function(){id.value='';clearTimeout(timer);if(search.value.trim().length<2){results.classList.add('hidden');return;}timer=setTimeout(async function(){try{const response=await fetch(@json(route('candidates.search'))+'?q='+encodeURIComponent(search.value.trim()),{headers:{Accept:'application/json'},cache:'no-store'});const data=await response.json();results.replaceChildren();(data.results||[]).forEach(function(item){const button=document.createElement('button');button.type='button';button.className='block w-full rounded-lg px-3 py-2 text-left text-sm text-white hover:bg-zinc-800';button.textContent=item.text;button.addEventListener('click',function(){id.value=item.id;search.value=item.text;results.classList.add('hidden');});results.appendChild(button);});results.classList.toggle('hidden',!results.children.length);}catch(e){results.classList.add('hidden');}},300);});form.querySelector('[data-clear-candidate]').addEventListener('click',function(){id.value='';search.value='';});});
</script>@endpush