@extends('layouts.app')

@section('page_title', 'Public Pulse')

@section('content')
<div class="space-y-6">
    <div class="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
        <div>
            <h1 class="text-3xl font-semibold text-white">Pulse Engine Jobs</h1>
            <p class="mt-1 text-sm text-zinc-400">Submit candidate monitoring jobs and review summaries generated by Pulse Engine.</p>
        </div>
        <div class="flex flex-wrap gap-2">
            <a href="{{ route('public-pulse.legacy') }}" class="rounded-xl border border-zinc-700 px-4 py-2 text-sm font-semibold text-zinc-300 hover:border-zinc-600 hover:text-white">Legacy Mentions</a>
            <a href="{{ route('public-pulse.x-sessions.index') }}" class="rounded-xl bg-emerald-600 px-4 py-2 text-sm font-semibold text-white hover:bg-emerald-500"><i class="fas fa-key mr-2"></i>X Sessions</a>
        </div>
    </div>

    @if(session('success'))
        <div class="rounded-2xl border border-emerald-500/30 bg-emerald-500/10 px-5 py-4 text-emerald-300">{{ session('success') }}</div>
    @endif
    @if(session('error'))
        <div class="rounded-2xl border border-red-500/30 bg-red-500/10 px-5 py-4 text-red-300">{{ session('error') }}</div>
    @endif

    <div class="grid gap-6 xl:grid-cols-[360px_minmax(0,1fr)]">
        <form method="POST" action="{{ route('public-pulse.jobs.store') }}" class="h-fit space-y-5 rounded-2xl border border-zinc-800 bg-zinc-900/60 p-5">
            @csrf
            <div>
                <h2 class="text-lg font-semibold text-white">Submit monitoring job</h2>
                <p class="mt-1 text-xs text-zinc-500">The candidate name is always included in the search.</p>
            </div>

            <x-aspirant-search
                name="candidate_id"
                :search-url="route('candidates.search')"
                label="Search candidate"
                placeholder="Type at least 2 characters..."
                help="Search by aspirant name or nickname."
                empty-text="No matching aspirant found."
                selection-note="Selected for this monitoring job."
                :selected-candidate="$submissionCandidate"
                :required="true"
            />

            <fieldset>
                <legend class="mb-2 text-sm text-zinc-400">Sources</legend>
                <div class="grid grid-cols-2 gap-2 sm:grid-cols-4">
                    @foreach(['x' => ['X', 'fa-x-twitter'], 'youtube' => ['YouTube', 'fa-youtube'], 'reddit' => ['Reddit', 'fa-reddit'], 'rss' => ['RSS', 'fas fa-rss']] as $source => [$label, $icon])
                        <label class="cursor-pointer rounded-xl border border-zinc-700 bg-zinc-950 p-3 text-center text-xs text-zinc-300 has-[:checked]:border-emerald-500 has-[:checked]:bg-emerald-500/10 has-[:checked]:text-emerald-300">
                            <input type="checkbox" name="sources[]" value="{{ $source }}" class="sr-only" @checked(in_array($source, old('sources', ['x']), true))>
                            <i class="{{ str_contains($icon, ' ') ? $icon : 'fab '. $icon }} mb-2 block text-lg"></i>{{ $label }}
                        </label>
                    @endforeach
                </div>
                <p class="mt-2 text-xs text-zinc-500">RSS searches Kenya-wide Google News plus configured feeds. News receives a separate Media Sentiment Score and never changes the Public Pulse Score.</p>
            </fieldset>
            <div>
                <label class="mb-2 block text-sm text-zinc-400">Extra keywords</label>
                <input name="keywords_text" value="{{ old('keywords_text') }}" class="w-full rounded-xl border border-zinc-700 bg-zinc-950 px-3 py-3 text-white placeholder:text-zinc-600" placeholder="housing levy, cost of living">
                <p class="mt-2 text-xs text-zinc-500">Separate multiple topics with commas.</p>
            </div>

            <div class="grid grid-cols-2 gap-3">
                <div><label class="mb-2 block text-sm text-zinc-400">From</label><input type="date" name="date_from" value="{{ old('date_from', now()->subDays(7)->toDateString()) }}" required class="w-full rounded-xl border border-zinc-700 bg-zinc-950 px-3 py-3 text-white [color-scheme:dark]"></div>
                <div><label class="mb-2 block text-sm text-zinc-400">To</label><input type="date" name="date_to" value="{{ old('date_to', now()->toDateString()) }}" required class="w-full rounded-xl border border-zinc-700 bg-zinc-950 px-3 py-3 text-white [color-scheme:dark]"></div>
            </div>

            <div>
                <label class="mb-2 block text-sm text-zinc-400">Mention limit</label>
                <input type="number" min="1" max="1000" name="limit" value="{{ old('limit', 20) }}" required class="w-full rounded-xl border border-zinc-700 bg-zinc-950 px-3 py-3 text-white">
            </div>

            @if($errors->any())
                <ul class="space-y-1 rounded-xl border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-300">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul>
            @endif

            <button class="w-full rounded-xl bg-emerald-600 px-5 py-3 font-semibold text-white hover:bg-emerald-500" data-loading-label="Submitting job..."><i class="fas fa-wave-square mr-2"></i>Submit job</button>
        </form>

        <div class="min-w-0 space-y-4">
            <form method="GET" class="grid gap-3 rounded-2xl border border-zinc-800 bg-zinc-900/60 p-4 sm:grid-cols-2 xl:grid-cols-5">
                <div class="sm:col-span-2 xl:col-span-1">
                    <x-aspirant-search
                        name="candidate_id"
                        :search-url="route('candidates.search')"
                        label="Candidate filter"
                        placeholder="Search candidate..."
                        help="Leave empty for all candidates."
                        empty-text="No matching aspirant found."
                        selection-note="Filtering by this candidate."
                        :selected-candidate="$filterCandidate"
                    />
                </div>
                <select name="status" class="rounded-xl border border-zinc-700 bg-zinc-950 px-3 py-2 text-sm text-white"><option value="">All statuses</option>@foreach(['submitting','submission_failed','queued_pending_capacity','queued','running','degraded','completed','failed'] as $status)<option value="{{ $status }}" @selected(($filters['status'] ?? null) === $status)>{{ str_replace('_', ' ', ucfirst($status)) }}</option>@endforeach</select>
                <input type="date" name="date_from" value="{{ $filters['date_from'] ?? '' }}" class="rounded-xl border border-zinc-700 bg-zinc-950 px-3 py-2 text-sm text-white [color-scheme:dark]">
                <input type="date" name="date_to" value="{{ $filters['date_to'] ?? '' }}" class="rounded-xl border border-zinc-700 bg-zinc-950 px-3 py-2 text-sm text-white [color-scheme:dark]">
                <button class="rounded-xl bg-zinc-800 px-4 py-2 text-sm font-semibold text-white hover:bg-zinc-700">Filter</button>
            </form>

            <div class="overflow-x-auto rounded-2xl border border-zinc-800 bg-zinc-900/60">
                <table class="min-w-full divide-y divide-zinc-800 text-sm">
                    <thead class="bg-zinc-950/70 text-left text-xs uppercase tracking-wider text-zinc-500"><tr><th class="px-4 py-3">Candidate</th><th class="px-4 py-3">Status</th><th class="px-4 py-3">Range / limit</th><th class="px-4 py-3">Summary</th><th class="px-4 py-3"></th></tr></thead>
                    <tbody class="divide-y divide-zinc-800 text-zinc-300">
                    @forelse($jobs as $job)
                        @php($terminal = in_array($job->status, ['completed', 'failed'], true))
                        <tr class="hover:bg-zinc-800/30">
                            <td class="px-4 py-4"><div class="font-semibold text-white">{{ $job->candidate?->name }}</div><div class="mt-1 font-mono text-[11px] text-zinc-600">{{ Str::limit($job->job_ref, 14) }}</div><div class="mt-2 flex flex-wrap gap-1">@foreach(($job->sources ?: ['x']) as $source)<span class="rounded bg-zinc-800 px-1.5 py-0.5 text-[10px] font-semibold uppercase text-zinc-400">{{ $source }}</span>@endforeach</div></td>
                            <td class="px-4 py-4"><span class="rounded-full px-3 py-1 text-xs font-semibold {{ $job->status === 'completed' ? 'bg-emerald-500/15 text-emerald-300' : ($job->status === 'failed' || $job->status === 'submission_failed' ? 'bg-red-500/15 text-red-300' : 'bg-amber-500/15 text-amber-300') }}">{{ str_replace('_', ' ', $job->status) }}</span>@if($job->partial)<div class="mt-2 text-xs text-amber-400">Partial result</div>@endif</td>
                            <td class="whitespace-nowrap px-4 py-4">{{ $job->date_from?->format('d M Y') }}<br><span class="text-zinc-500">to {{ $job->date_to?->format('d M Y') }} � {{ $job->requested_limit }}</span></td>
                            <td class="px-4 py-4"><div class="font-semibold text-white">Score: {{ data_get($job->summary, 'pulse_score', '�') }}</div><div class="mt-1 text-xs text-zinc-500">Confidence: {{ data_get($job->summary, 'overall_confidence', '�') }}</div></td>
                            <td class="px-4 py-4 text-right"><a class="rounded-lg border border-zinc-700 px-3 py-2 text-xs font-semibold text-zinc-300 hover:border-emerald-500/50 hover:text-emerald-300" href="{{ route('public-pulse.jobs.show', $job) }}">Open</a></td>
                        </tr>
                    @empty
                        <tr><td colspan="5" class="px-4 py-14 text-center"><i class="fas fa-wave-square mb-3 block text-3xl text-zinc-700"></i><span class="text-zinc-500">No Pulse Engine jobs yet.</span></td></tr>
                    @endforelse
                    </tbody>
                </table>
            </div>
            <div>{{ $jobs->withQueryString()->links() }}</div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script>
document.querySelector('form[action="{{ route('public-pulse.jobs.store') }}"]')?.addEventListener('submit', function () {
    const field = this.querySelector('[name="keywords_text"]');
    field.value.split(',').map(value => value.trim()).filter(Boolean).forEach(value => {
        const input = document.createElement('input'); input.type = 'hidden'; input.name = 'keywords[]'; input.value = value; this.appendChild(input);
    });
    field.removeAttribute('name');
});
</script>
@endpush
