<?php
namespace App\Services\Web;
use App\Models\Candidate;
use App\Models\CandidateTokenPackage;
use App\Models\CandidateTokenTransaction;
use App\Models\CandidateTokenWallet;
use App\Models\PoliticalParty;
use App\Models\PoliticalPartyTokenPurchase;
use App\Models\PoliticalPartyTokenTransaction;
use App\Models\PoliticalPartyTokenTransfer;
use App\Models\PoliticalPartyTokenWallet;
use App\Models\User;
use App\Services\Api\IpayService;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use RuntimeException;
class PoliticalPartyTokenService {
 public function __construct(private IpayService $ipay){}
 public function wallet(PoliticalParty $party): PoliticalPartyTokenWallet { return PoliticalPartyTokenWallet::firstOrCreate(['political_party_id'=>$party->id],['balance'=>0]); }
 public function purchase(PoliticalParty $party, User $user, CandidateTokenPackage $package, array $contact): string { $this->ipay->assertConfigured(); $purchase=PoliticalPartyTokenPurchase::create(['political_party_id'=>$party->id,'user_id'=>$user->id,'candidate_token_package_id'=>$package->id,'checkout_reference'=>'PTY'.now()->format('ymdHis').Str::upper(Str::random(8)),'package_name'=>$package->name,'token_amount'=>$package->token_amount,'price'=>$package->price,'currency'=>$package->currency,'status'=>'pending']); return $this->ipay->partyCheckoutUrl($purchase,$user,$package,$contact); }
 public function callback(array $data): array { $ref=$this->ipay->callbackReference($data); if(!$ref) return ['status'=>'failed','message'=>'Missing payment reference.']; $verification=$this->ipay->verifyTransaction($ref); return DB::transaction(function()use($ref,$verification,$data){ $purchase=PoliticalPartyTokenPurchase::where('checkout_reference',$ref)->lockForUpdate()->first(); if(!$purchase)return ['status'=>'failed','message'=>'Party token purchase not found.']; $gateway=['gateway_transaction_code'=>$verification['transaction_code'],'gateway_status'=>$verification['status'],'gateway_response'=>['callback'=>$data,'verification'=>$verification['raw']],'callback_received_at'=>now()]; if($purchase->status==='credited'){ $purchase->update($gateway); return ['status'=>'success','message'=>'This purchase was already credited.']; } if($verification['status']!=='success'||abs((float)$verification['amount']-(float)$purchase->price)>=.01){$purchase->update($gateway+['status'=>'failed']);return ['status'=>'failed','message'=>'Payment was not confirmed for the expected amount.'];} $wallet=PoliticalPartyTokenWallet::where('political_party_id',$purchase->political_party_id)->lockForUpdate()->first()?:PoliticalPartyTokenWallet::create(['political_party_id'=>$purchase->political_party_id,'balance'=>0]); $before=$wallet->balance;$wallet->update(['balance'=>$before+$purchase->token_amount]); PoliticalPartyTokenTransaction::create(['political_party_id'=>$purchase->political_party_id,'political_party_token_wallet_id'=>$wallet->id,'user_id'=>$purchase->user_id,'political_party_token_purchase_id'=>$purchase->id,'type'=>'purchase','amount'=>$purchase->token_amount,'balance_before'=>$before,'balance_after'=>$wallet->balance,'metadata'=>['reference'=>$ref],'finalized_at'=>now()]);$purchase->update($gateway+['status'=>'credited','payment_reference'=>$verification['transaction_code']?:$ref,'credited_at'=>now()]);return ['status'=>'success','message'=>number_format($purchase->token_amount).' tokens credited to the party wallet.'];}); }
 public function transfer(PoliticalParty $party, Candidate $candidate, User $user, int $amount): void { if($amount<1)throw new RuntimeException('Enter at least one token.'); if($candidate->political_party_id!==$party->id||$candidate->approval_status!=='approved')throw new RuntimeException('Tokens can only be distributed to approved aspirants in this party.'); DB::transaction(function()use($party,$candidate,$user,$amount){$partyWallet=$this->wallet($party);$partyWallet=PoliticalPartyTokenWallet::whereKey($partyWallet->id)->lockForUpdate()->firstOrFail();if($partyWallet->balance<$amount)throw new RuntimeException('Insufficient party token balance.');$candidateWallet=CandidateTokenWallet::firstOrCreate(['candidate_id'=>$candidate->id],['balance'=>0]);$candidateWallet=CandidateTokenWallet::whereKey($candidateWallet->id)->lockForUpdate()->firstOrFail();$partyBefore=$partyWallet->balance;$candidateBefore=$candidateWallet->balance;$partyWallet->update(['balance'=>$partyBefore-$amount]);$candidateWallet->update(['balance'=>$candidateBefore+$amount]);$partyTx=PoliticalPartyTokenTransaction::create(['political_party_id'=>$party->id,'political_party_token_wallet_id'=>$partyWallet->id,'user_id'=>$user->id,'candidate_id'=>$candidate->id,'type'=>'distribution','amount'=>-$amount,'balance_before'=>$partyBefore,'balance_after'=>$partyWallet->balance,'metadata'=>['candidate'=>$candidate->name],'finalized_at'=>now()]);$candidateTx=CandidateTokenTransaction::create(['candidate_id'=>$candidate->id,'candidate_token_wallet_id'=>$candidateWallet->id,'user_id'=>$user->id,'type'=>'party_transfer','status'=>'completed','action_label'=>'Tokens from '.$party->name,'calculation_type'=>'fixed','quantity'=>1,'unit_tokens'=>$amount,'amount'=>$amount,'balance_before'=>$candidateBefore,'balance_after'=>$candidateWallet->balance,'metadata'=>['political_party_id'=>$party->id],'finalized_at'=>now()]);PoliticalPartyTokenTransfer::create(['political_party_id'=>$party->id,'candidate_id'=>$candidate->id,'user_id'=>$user->id,'party_transaction_id'=>$partyTx->id,'candidate_transaction_id'=>$candidateTx->id,'amount'=>$amount]);}); }
}