@php($package = $candidateTokenPackage ?? null)
<div class="grid grid-cols-1 md:grid-cols-2 gap-6">
    <div><label class="block text-sm text-zinc-400 mb-2">Name</label><input name="name" value="{{ old('name', $package?->name) }}" required class="w-full bg-zinc-800 border border-zinc-700 rounded-2xl px-4 py-3 text-white">@error('name')<p class="text-red-400 text-sm mt-2">{{ $message }}</p>@enderror</div>
    <div><label class="block text-sm text-zinc-400 mb-2">Tokens</label><input type="number" min="1" name="token_amount" value="{{ old('token_amount', $package?->token_amount) }}" required class="w-full bg-zinc-800 border border-zinc-700 rounded-2xl px-4 py-3 text-white">@error('token_amount')<p class="text-red-400 text-sm mt-2">{{ $message }}</p>@enderror</div>
    <div><label class="block text-sm text-zinc-400 mb-2">Price</label><input type="number" min="0" name="price" value="{{ old('price', $package?->price) }}" required class="w-full bg-zinc-800 border border-zinc-700 rounded-2xl px-4 py-3 text-white">@error('price')<p class="text-red-400 text-sm mt-2">{{ $message }}</p>@enderror</div>
    <div><label class="block text-sm text-zinc-400 mb-2">Currency</label><input name="currency" maxlength="3" value="{{ old('currency', $package?->currency ?? 'KES') }}" required class="w-full bg-zinc-800 border border-zinc-700 rounded-2xl px-4 py-3 text-white">@error('currency')<p class="text-red-400 text-sm mt-2">{{ $message }}</p>@enderror</div>
    <div><label class="block text-sm text-zinc-400 mb-2">Sort Order</label><input type="number" min="0" name="sort_order" value="{{ old('sort_order', $package?->sort_order ?? 0) }}" class="w-full bg-zinc-800 border border-zinc-700 rounded-2xl px-4 py-3 text-white"></div>
    <label class="flex items-center gap-3 mt-8"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" {{ old('is_active', $package?->is_active ?? true) ? 'checked' : '' }}> Active</label>
</div>
<div class="mt-6"><label class="block text-sm text-zinc-400 mb-2">Description</label><textarea name="description" rows="4" class="w-full bg-zinc-800 border border-zinc-700 rounded-2xl px-4 py-3 text-white">{{ old('description', $package?->description) }}</textarea></div>
