<?php

return [
    'brand' => [
        'label' => 'Aspirant',
        'title' => 'Dashboard',
    ],

    'items' => [
        [
            'label' => 'Analytics',
            'icon' => 'fas fa-chart-line',
            'route' => 'aspirant.dashboard',
            'fragment' => 'analytics',
            'section' => 'analytics',
        ],
        [
            'label' => 'Campaign Tools',
            'icon' => 'fas fa-toolbox',
            'route' => 'aspirant.dashboard',
            'fragment' => 'campaign-tools',
            'section' => 'campaign-tools',
        ],
        [
            'label' => 'Submit News',
            'icon' => 'fas fa-pen-to-square',
            'route' => 'aspirant.news.create',
            'active' => ['aspirant.news.create'],
        ],
        [
            'label' => 'My News',
            'icon' => 'fas fa-newspaper',
            'route' => 'aspirant.news.index',
            'active' => ['aspirant.news.index'],
        ],
        [
            'label' => 'My Events',
            'icon' => 'fas fa-calendar-plus',
            'route' => 'aspirant.events.index',
            'active' => ['aspirant.events.*'],
        ],
        [
            'label' => 'Bulk SMS',
            'icon' => 'fas fa-comment-sms',
            'route' => 'aspirant.tools.show',
            'params' => ['bulk-sms'],
            'active' => ['aspirant.tools.show'],
            'tool_key' => 'bulk-sms',
        ],
        [
            'label' => 'Opinion Polls',
            'icon' => 'fas fa-square-poll-vertical',
            'route' => 'aspirant.tools.show',
            'params' => ['opinion-polls'],
            'active' => ['aspirant.tools.show'],
            'tool_key' => 'opinion-polls',
        ],
        [
            'label' => 'Campaign Website',
            'icon' => 'fas fa-globe',
            'route' => 'aspirant.tools.show',
            'params' => ['campaign-website'],
            'active' => ['aspirant.tools.show'],
            'tool_key' => 'campaign-website',
        ],
        [
            'label' => 'Support Groups',
            'icon' => 'fas fa-people-group',
            'route' => 'aspirant.tools.show',
            'params' => ['support-groups'],
            'active' => ['aspirant.tools.show'],
            'tool_key' => 'support-groups',
        ],
        [
            'label' => 'Call Center',
            'icon' => 'fas fa-headset',
            'route' => 'aspirant.tools.show',
            'params' => ['call-center'],
            'active' => ['aspirant.tools.show'],
            'tool_key' => 'call-center',
        ],
        [
            'label' => 'Campaign Priorities',
            'icon' => 'fas fa-bullseye',
            'href' => '#campaign-priorities',
            'section' => 'campaign-priorities',
        ],
        [
            'label' => 'Profile',
            'icon' => 'fas fa-id-badge',
            'href' => '#profile',
            'section' => 'profile',
        ],
        [
            'label' => 'Recent Outreach',
            'icon' => 'fas fa-paper-plane',
            'href' => '#recent-outreach',
            'section' => 'recent-outreach',
        ],
        [
            'label' => 'Poll Snapshot',
            'icon' => 'fas fa-chart-simple',
            'href' => '#poll-snapshot',
            'section' => 'poll-snapshot',
        ],
        [
            'label' => 'Audit History',
            'icon' => 'fas fa-clock-rotate-left',
            'route' => 'aspirant.audits.index',
            'active' => ['aspirant.audits.*'],
        ],
        [
            'label' => 'Token Wallet',
            'icon' => 'fas fa-coins',
            'route' => 'aspirant.tokens.index',
            'active' => ['aspirant.tokens.*'],
        ],
        [
            'label' => 'Support Received',
            'icon' => 'fas fa-hand-holding-heart',
            'route' => 'aspirant.support.index',
            'active' => ['aspirant.support.*'],
        ],
    ],
];
