<?php

return [

    'counties' => [
        'Mombasa', 'Kwale', 'Kilifi', 'Tana River', 'Lamu', 'Taita Taveta',
        'Garissa', 'Wajir', 'Mandera', 'Marsabit', 'Isiolo', 'Meru',
        'Tharaka Nithi', 'Embu', 'Kitui', 'Machakos', 'Makueni', 'Nyandarua',
        'Nyeri', 'Kirinyaga', 'Murang\'a', 'Kiambu', 'Turkana', 'West Pokot',
        'Samburu', 'Trans Nzoia', 'Uasin Gishu', 'Elgeyo Marakwet', 'Nandi',
        'Baringo', 'Laikipia', 'Nakuru', 'Narok', 'Kajiado', 'Kericho',
        'Bomet', 'Kakamega', 'Vihiga', 'Bungoma', 'Busia', 'Siaya', 'Kisumu',
        'Homa Bay', 'Migori', 'Kisii', 'Nyamira', 'Nairobi'
    ],
    'constituencies' =>[
        'Mombasa'       => ['Changamwe', 'Jomvu', 'Kisauni', 'Likoni', 'Mvita', 'Nyali'],
        'Kwale'         => ['Kinango', 'Lunga Lunga', 'Matuga', 'Msambweni'],
        'Kilifi'        => ['Ganze', 'Kaloleni', 'Kilifi North', 'Kilifi South', 'Malindi', 'Rabai'],
        'Tana River'    => ['Bura', 'Galole', 'Garsen'],
        'Lamu'          => ['Lamu East', 'Lamu West'],
        'Taita Taveta'  => ['Mwatate', 'Taveta', 'Voi', 'Wundanyi'],
        'Garissa'       => ['Dadaab', 'Fafi', 'Garissa Township', 'Lagdera'],
        'Wajir'         => ['Eldas', 'Tarbaj', 'Wajir East', 'Wajir North', 'Wajir South', 'Wajir West'],
        'Mandera'       => ['Banissa', 'Lafey', 'Mandera East', 'Mandera North', 'Mandera South', 'Mandera West'],
        'Marsabit'      => ['Chalbi', 'Laisamis', 'Moyale', 'North Horr', 'Saku'],
        'Isiolo'        => ['Garbatulla', 'Isiolo', 'Merti'],
        'Meru'          => ['Buuri', 'Central Imenti', 'Igembe Central', 'Igembe North', 'Igembe South', 'North Imenti', 'South Imenti', 'Tigania East', 'Tigania West'],
        'Tharaka Nithi' => ['Chuka', 'Maara', 'Tharaka'],
        'Embu'          => ['Manyatta', 'Mbeere North', 'Mbeere South', 'Runyenjes'],
        'Kitui'         => ['Kitui Central', 'Kitui East', 'Kitui Rural', 'Kitui South', 'Kitui West', 'Mwingi Central', 'Mwingi North', 'Mwingi West'],
        'Machakos'      => ['Kangundo', 'Kathiani', 'Machakos Town', 'Masinga', 'Matungulu', 'Mavoko', 'Mwala'],
        'Makueni'       => ['Kaiti', 'Kibwezi East', 'Kibwezi West', 'Kilome', 'Makueni', 'Mbooni'],
        'Nyandarua'     => ['Kinangop', 'Kipipiri', 'Ndaragwa', 'Ol Jorok', 'Ol Kalou'],
        'Nyeri'         => ['Kieni', 'Mathira East', 'Mathira West', 'Mukurweini', 'Nyeri Town', 'Othaya', 'Tetu'],
        'Kirinyaga'     => ['Gichugu', 'Kirinyaga Central', 'Mwea'],
        "Murang'a"      => ['Gatanga', 'Kahuro', 'Kangema', 'Kigumo', 'Kiharu', 'Mathioya'],
        'Kiambu'        => ['Gatundu North', 'Gatundu South', 'Githunguri', 'Juja', 'Kabete', 'Kiambaa', 'Kiambu', 'Kikuyu', 'Limuru', 'Ruiru', 'Thika Town'],
        'Turkana'       => ['Loima', 'Turkana Central', 'Turkana East', 'Turkana North', 'Turkana South', 'Turkana West'],
        'West Pokot'    => ['Kacheliba', 'Kapenguria', 'Konyar', 'Pokot South'],
        'Samburu'       => ['Samburu East', 'Samburu North', 'Samburu West'],
        'Trans Nzoia'   => ['Cherangany', 'Endebess', 'Kiminin', 'Kwanza', 'Saboti'],
        'Uasin Gishu'   => ['Ainabkoi', 'Kapseret', 'Kesses', 'Soy', 'Turbo'],
        'Elgeyo Marakwet'=> ['Keiyo North', 'Keiyo South', 'Marakwet East', 'Marakwet West'],
        'Nandi'         => ['Aldai', 'Chesumei', 'Emgwen', 'Mosop', 'Nandi Hills', 'Tinderet'],
        'Baringo'       => ['Baringo Central', 'Baringo East', 'Baringo North', 'Baringo South', 'Mogotio', 'Tiaty'],
        'Laikipia'      => ['Laikipia East', 'Laikipia North', 'Laikipia West'],
        'Nakuru'        => ['Bahati', 'Gilgil', 'Kuresoi North', 'Kuresoi South', 'Molo', 'Naivasha', 'Nakuru Town East', 'Nakuru Town West', 'Njoro', 'Rongai', 'Subukia'],
        'Narok'         => ['Emurua Dikirr', 'Kilgoris', 'Narok East', 'Narok North', 'Narok South', 'Narok West'],
        'Kajiado'       => ['Kajiado Central', 'Kajiado East', 'Kajiado North', 'Kajiado South', 'Kajiado West'],
        'Kericho'       => ['Ainamoi', 'Belgut', 'Bureti', 'Kipkelion East', 'Kipkelion West', 'Sigowet-Soin'],
        'Bomet'         => ['Bomet Central', 'Bomet East', 'Chepalungu', 'Konoin', 'Sotik'],
        'Kakamega'      => ['Butere', 'Ikolomani', 'Kakamega Central', 'Kakamega East', 'Kakamega North', 'Kakamega South', 'Khwisero', 'Lugari', 'Lurambi', 'Malava', 'Shinyalu'],
        'Vihiga'        => ['Emuhaya', 'Hamisi', 'Luanda', 'Sabatia', 'Vihiga'],
        'Bungoma'       => ['Bumula', 'Kabuchai', 'Kanduyi', 'Kimilili', 'Mt. Elgon', 'Sirisia', 'Tongaren', 'Webuye East', 'Webuye West'],
        'Busia'         => ['Budalangi', 'Butula', 'Funyula', 'Matayos', 'Nambale', 'Teso North', 'Teso South'],
        'Siaya'         => ['Alego Usonga', 'Bondo', 'Gem', 'Rarieda', 'Ugenya', 'Ugunja'],
        'Kisumu'        => ['Kisumu Central', 'Kisumu East', 'Kisumu West', 'Muhoroni', 'Nyakach', 'Nyando', 'Seme'],
        'Homa Bay'      => ['Homa Bay Town', 'Karachuonyo', 'Kasipul', 'Kabondo Kasipul', 'Ndhiwa', 'Rangwe', 'Suba'],
        'Migori'        => ['Awendo', 'Kuria East', 'Kuria West', 'Migori', 'Nyatike', 'Rongo', 'Suna East', 'Suna West'],
        'Kisii'         => ['Bobasi', 'Bomachoge Borabu', 'Bomachoge Chache', 'Nyaribari Chache', 'Nyaribari Masaba', 'South Mugirango'],
        'Nyamira'       => ['Borabu', 'Kitutu Masaba', 'North Mugirango', 'West Mugirango'],
        'Nairobi'       => ['Westlands', 'Dagoretti North', 'Dagoretti South', "Lang'ata", 'Kibra', 'Roysambu', 'Kasarani', 'Ruaraka', 'Embakasi South', 'Embakasi North', 'Embakasi Central', 'Embakasi East', 'Embakasi West', 'Makadara', 'Kamukunji', 'Starehe', 'Mathare'],
    ],
];