@extends('layouts.landing')
@section('title', 'My Toolbox - My Leader Kenya')
@push('styles')
@include('account.partials.news-styles')
<style>
.toolbox-balance{display:flex;align-items:center;justify-content:space-between;gap:20px;padding:24px;border:1px solid rgba(16,185,129,.3);border-radius:22px;background:linear-gradient(135deg,rgba(16,185,129,.15),rgba(9,9,11,.9))}.toolbox-balance strong{display:block;font:700 42px 'Oswald',sans-serif;color:#6ee7b7}.toolbox-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;margin-top:18px}.toolbox-card{border:1px solid #29292d;border-radius:20px;background:#151517;padding:20px}.toolbox-card h2,.toolbox-card h3{color:#fff}.toolbox-muted{color:#a1a1aa}.toolbox-section{margin-top:34px}.toolbox-form{display:grid;gap:10px;margin-top:15px}.toolbox-input{width:100%;border:1px solid #3f3f46;border-radius:12px;background:#242427;color:#fff;padding:11px 13px}.toolbox-button{display:inline-flex;align-items:center;justify-content:center;border:0;border-radius:12px;background:#059669;padding:12px 17px;color:#fff;font-weight:800;cursor:pointer}.toolbox-button:disabled{background:#3f3f46;color:#a1a1aa;cursor:not-allowed}.toolbox-list{display:grid;gap:12px;margin-top:16px}.toolbox-row{display:flex;align-items:center;justify-content:space-between;gap:18px;border:1px solid #29292d;border-radius:16px;background:#151517;padding:17px}.toolbox-tags{display:flex;flex-wrap:wrap;gap:7px;margin-top:9px}.toolbox-tag,.toolbox-status{border-radius:999px;background:rgba(16,185,129,.12);padding:5px 9px;color:#6ee7b7;font-size:12px;font-weight:800}.toolbox-status.awaiting_payment{background:rgba(245,158,11,.13);color:#fbbf24}.toolbox-status.refunded{background:rgba(96,165,250,.13);color:#93c5fd}.toolbox-status.failed{background:rgba(239,68,68,.13);color:#fca5a5}.toolbox-alert{margin-top:15px;border-radius:14px;padding:13px 16px}.toolbox-alert.success{background:rgba(16,185,129,.13);color:#a7f3d0}.toolbox-alert.warning,.toolbox-alert.error{background:rgba(245,158,11,.13);color:#fde68a}.toolbox-amount.in{color:#6ee7b7}.toolbox-amount.out{color:#fca5a5}@media(max-width:900px){.toolbox-grid{grid-template-columns:1fr}.toolbox-row{align-items:flex-start;flex-direction:column}}
</style>
@endpush
@section('content')
<div class="flag-stripe"></div>@include('components.frontend-nav')
<main class="news-account-shell"><div class="news-account-layout">
@include('components.my-account-sidebar')
<section class="news-account-content">
<p class="news-kicker">Donor Toolbox</p><h1 class="news-title">Sponsor campaign tools</h1><p class="news-subtitle">Buy tokens once, fund several aspirants, and track every payment or refund from your personal wallet.</p>
@if(session('success'))<div class="toolbox-alert success">{{ session('success') }}</div>@endif
@if(session('warning'))<div class="toolbox-alert warning">{{ session('warning') }}</div>@endif
@if($errors->any())<div class="toolbox-alert error">{{ $errors->first() }}</div>@endif
<div class="toolbox-balance toolbox-section"><div><span class="toolbox-muted">Available balance</span><strong>{{ number_format($wallet->balance) }} tokens</strong></div><i class="fas fa-toolbox text-4xl text-emerald-400"></i></div>
<section class="toolbox-section"><h2 class="news-title" style="font-size:30px">Top up your Toolbox</h2><p class="toolbox-muted">Purchased tokens stay in your personal wallet until you choose a sponsorship.</p><div class="toolbox-grid">
@forelse($packages as $package)<article class="toolbox-card"><h3 class="text-xl font-bold">{{ $package->name }}</h3><p class="mt-2 text-3xl font-bold text-emerald-300">{{ number_format($package->token_amount) }} tokens</p><p class="toolbox-muted">{{ $package->currency }} {{ number_format($package->price, 2) }}</p><form method="POST" action="{{ route('account.toolbox.purchase') }}" class="toolbox-form">@csrf<input type="hidden" name="candidate_token_package_id" value="{{ $package->id }}"><input class="toolbox-input" name="phone" value="{{ old('phone', auth()->user()->phone) }}" placeholder="Payment phone" required><input class="toolbox-input" type="email" name="email" value="{{ old('email', auth()->user()->email) }}" placeholder="Receipt email" required><button class="toolbox-button"><i class="fas fa-wallet mr-2"></i> Buy tokens</button></form></article>
@empty<div class="toolbox-card toolbox-muted">No token packages are available right now.</div>@endforelse
</div></section>
<section class="toolbox-section"><h2 class="news-title" style="font-size:30px">My sponsorship requests</h2><div class="toolbox-list">
@forelse($adoptions as $adoption)<article class="toolbox-row"><div><h3 class="text-xl font-bold text-white">{{ $adoption->candidate->name ?? 'Aspirant' }}</h3><div class="toolbox-tags">@foreach($adoption->selectedTools as $tool)<span class="toolbox-tag">{{ $tool->title }}</span>@endforeach</div>@if($adoption->payment_status === 'paid' || $adoption->payment_status === 'refunded')<p class="toolbox-muted mt-2">Sponsorship amount: <strong class="text-white">{{ number_format($adoption->tokens_required) }} tokens</strong></p>@endif</div><div class="text-right"><span class="toolbox-status {{ $adoption->payment_status }}">{{ str_replace('_',' ',ucfirst($adoption->payment_status)) }}</span>@if($adoption->payment_status === 'awaiting_payment' && $adoption->status !== 'cancelled')<form method="POST" action="{{ route('account.toolbox.adoptions.pay', $adoption) }}" class="toolbox-form mt-3">@csrf<label class="toolbox-muted text-sm" for="sponsorship-{{ $adoption->id }}">Amount you want to sponsor</label><input class="toolbox-input" id="sponsorship-{{ $adoption->id }}" type="number" name="token_amount" min="1" max="{{ $wallet->balance }}" placeholder="Enter tokens" required><button class="toolbox-button" {{ $wallet->balance < 1 ? 'disabled' : '' }}>Sponsor from Toolbox</button></form>@endif</div></article>
@empty<div class="toolbox-card toolbox-muted">You have no sponsorship requests yet. Start with &quot;Adopt An Aspirant&quot;.</div>@endforelse
</div></section>
<section class="toolbox-section"><h2 class="news-title" style="font-size:30px">Transaction history</h2><div class="toolbox-list">@forelse($transactions as $transaction)<article class="toolbox-row"><div><h3 class="font-bold text-white">{{ $transaction->action_label }}</h3><p class="toolbox-muted">{{ $transaction->candidate->name ?? 'Personal Toolbox' }} - {{ $transaction->created_at->format('d M Y, H:i') }}</p></div><strong class="toolbox-amount {{ $transaction->amount >= 0 ? 'in' : 'out' }}">{{ $transaction->amount >= 0 ? '+' : '' }}{{ number_format($transaction->amount) }} tokens</strong></article>@empty<div class="toolbox-card toolbox-muted">No Toolbox transactions yet.</div>@endforelse</div></section>
<section class="toolbox-section"><h2 class="news-title" style="font-size:30px">Purchase history</h2><div class="toolbox-list">@forelse($purchases as $purchase)<article class="toolbox-row"><div><h3 class="font-bold text-white">{{ $purchase->package_name }}</h3><p class="toolbox-muted">{{ $purchase->currency }} {{ number_format($purchase->price,2) }} - {{ $purchase->created_at->format('d M Y, H:i') }}</p></div><span class="toolbox-status {{ $purchase->status }}">{{ ucfirst($purchase->status) }}</span></article>@empty<div class="toolbox-card toolbox-muted">No token purchases yet.</div>@endforelse</div></section>
</section></div></main>
@endsection