@extends('layouts.landing')
@section('title', $party->name.' Party Dashboard')
@section('content')
@include('components.frontend-nav')
<style>
:root{--pd-bg:#090b0b;--pd-card:#141716;--pd-soft:#1d211f;--pd-line:rgba(255,255,255,.08);--pd-muted:#8c9691;--pd-green:#00a873;--pd-white:#f5f7f6}
.pd-workspace{min-height:calc(100vh - 90px);padding:28px;background:var(--pd-bg);color:var(--pd-white)}
.pd-shell{display:grid;grid-template-columns:270px minmax(0,1fr);gap:24px;width:min(1500px,100%);margin:auto}
.pd-sidebar{position:sticky;top:110px;align-self:start;overflow:hidden;border:1px solid var(--pd-line);border-radius:22px;background:#101312}
.pd-brand{padding:24px;border-bottom:1px solid var(--pd-line);background:linear-gradient(145deg,rgba(0,168,115,.16),transparent 70%)}
.pd-kicker{margin:0 0 8px;color:var(--pd-green);font-size:11px;font-weight:800;letter-spacing:1.5px;text-transform:uppercase}.pd-brand h1{margin:0;font-size:23px;line-height:1.2}.pd-role{margin:8px 0 0;color:var(--pd-muted);font-size:13px}
.pd-balance{margin-top:20px;padding:15px;border:1px solid rgba(0,168,115,.23);border-radius:14px;background:rgba(0,0,0,.2)}.pd-balance span{display:block;color:var(--pd-muted);font-size:11px;text-transform:uppercase}.pd-balance strong{display:block;margin-top:5px;font-size:25px}
.pd-nav{display:grid;gap:5px;padding:14px}.pd-nav button{display:flex;align-items:center;gap:12px;width:100%;padding:12px 14px;border:0;border-radius:11px;background:transparent;color:#aeb5b2;font:inherit;text-align:left;cursor:pointer}.pd-nav button i{width:19px;color:#65706c;text-align:center}.pd-nav button:hover,.pd-nav button.active{background:rgba(0,168,115,.12);color:white}.pd-nav button.active i{color:var(--pd-green)}
.pd-add{display:block;margin:4px 14px 18px;padding:12px;border-radius:11px;background:var(--pd-green);color:white;font-weight:700;text-align:center;text-decoration:none}.pd-main{min-width:0}.pd-panel{display:none}.pd-panel.active{display:block}
.pd-alert{margin-bottom:16px;padding:14px 17px;border:1px solid var(--pd-line);border-radius:12px;background:var(--pd-card)}.pd-alert.success{border-color:rgba(0,168,115,.5)}.pd-alert.error,.pd-alert.warning{border-color:rgba(220,80,65,.5)}.pd-alert ul{margin:0;padding-left:20px}
.pd-heading{display:flex;align-items:flex-end;justify-content:space-between;gap:18px;margin-bottom:22px}.pd-heading h2{margin:0 0 6px;font-size:clamp(28px,3vw,38px)}.pd-heading p,.pd-muted{margin:0;color:var(--pd-muted)}
.pd-stats,.pd-cols,.pd-form-grid{display:grid;gap:16px}.pd-stats{grid-template-columns:repeat(4,minmax(0,1fr))}.pd-cols,.pd-form-grid{grid-template-columns:repeat(2,minmax(0,1fr))}
.pd-stat,.pd-card{padding:22px;border:1px solid var(--pd-line);border-radius:18px;background:var(--pd-card)}.pd-stat{background:linear-gradient(145deg,var(--pd-soft),var(--pd-card))}.pd-stat span{color:var(--pd-muted);font-size:12px;font-weight:700;text-transform:uppercase}.pd-stat strong{display:block;margin-top:8px;font-size:31px}.pd-card h3{margin-top:0}
.pd-field{display:grid;gap:7px}.pd-field label{color:#bec5c1;font-size:12px;font-weight:700}.pd-field input,.pd-field select{width:100%;min-height:44px;padding:10px 13px;border:1px solid #343a38;border-radius:10px;background:#202422;color:white}.pd-field input:focus,.pd-field select:focus{border-color:var(--pd-green);outline:0;box-shadow:0 0 0 3px rgba(0,168,115,.1)}
.pd-form{display:grid;gap:12px}.pd-inline{display:grid;grid-template-columns:minmax(180px,1fr) minmax(120px,.45fr) auto;gap:12px;align-items:end}.pd-btn{display:inline-flex;align-items:center;justify-content:center;gap:8px;min-height:43px;padding:10px 16px;border:0;border-radius:10px;background:var(--pd-green);color:white;font:inherit;font-weight:700;text-decoration:none;cursor:pointer}.pd-btn.secondary{border:1px solid var(--pd-line);background:#232725}.pd-btn.danger{background:#7f1d1d}
.pd-table-wrap{overflow-x:auto}.pd-table{width:100%;border-collapse:collapse}.pd-table th,.pd-table td{padding:14px 12px;border-bottom:1px solid var(--pd-line);text-align:left;white-space:nowrap}.pd-table th{color:var(--pd-muted);font-size:11px;text-transform:uppercase}.pd-list{display:grid;gap:11px}.pd-item{padding:14px;border:1px solid var(--pd-line);border-radius:12px;background:rgba(255,255,255,.02)}.pd-item-row{display:flex;align-items:center;justify-content:space-between;gap:14px}.pd-empty{padding:26px;color:var(--pd-muted);text-align:center}.pd-pagination{margin-top:18px}
@media(max-width:1050px){.pd-shell{grid-template-columns:225px minmax(0,1fr)}.pd-stats{grid-template-columns:repeat(2,1fr)}}
@media(max-width:780px){.pd-workspace{padding:18px}.pd-shell{display:block}.pd-sidebar{position:static;margin-bottom:20px}.pd-brand{padding:18px}.pd-nav{display:flex;overflow-x:auto;padding:10px}.pd-nav button{flex:0 0 auto;width:auto;white-space:nowrap}.pd-cols,.pd-form-grid,.pd-inline{grid-template-columns:1fr}}
@media(max-width:520px){.pd-workspace{padding:12px}.pd-stats{grid-template-columns:1fr}.pd-card{padding:17px}.pd-heading{align-items:flex-start;flex-direction:column}}
</style>
<main class="pd-workspace"><div class="pd-shell">
<aside class="pd-sidebar" aria-label="Party dashboard navigation">
<div class="pd-brand"><p class="pd-kicker">Political Party Workspace</p><h1>{{ $party->name }}</h1><p class="pd-role">{{ str($membership->role)->headline() }}</p><div class="pd-balance"><span>Party token balance</span><strong>{{ number_format($wallet->balance) }}</strong></div></div>
<nav class="pd-nav">
<button type="button" data-panel="overview"><i class="fas fa-chart-pie"></i>Overview</button>
<button type="button" data-panel="aspirants"><i class="fas fa-user-tie"></i>Aspirants</button>
<button type="button" data-panel="claims"><i class="fas fa-file-signature"></i>Claims</button>
<button type="button" data-panel="tokens"><i class="fas fa-coins"></i>Tokens</button>
<button type="button" data-panel="transactions"><i class="fas fa-receipt"></i>Transactions</button>
@if($membership->role === 'party_admin')<button type="button" data-panel="officials"><i class="fas fa-users-cog"></i>Officials</button>@endif
</nav><a class="pd-add" href="{{ route('party.candidates.create') }}"><i class="fas fa-plus"></i> Add Aspirant</a>
</aside>
<div class="pd-main">
@if(session('success'))<div class="pd-alert success">{{ session('success') }}</div>@endif
@if(session('warning'))<div class="pd-alert warning">{{ session('warning') }}</div>@endif
@if($errors->any())<div class="pd-alert error"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<section class="pd-panel" data-content="overview">
<div class="pd-heading"><div><h2>Dashboard overview</h2><p>Party activity and workspace summary.</p></div><a class="pd-btn" href="{{ route('party.candidates.create') }}"><i class="fas fa-plus"></i>Add Aspirant</a></div>
<div class="pd-stats"><div class="pd-stat"><span>Party tokens</span><strong>{{ number_format($wallet->balance) }}</strong></div><div class="pd-stat"><span>Aspirants</span><strong>{{ number_format($candidates->total()) }}</strong></div><div class="pd-stat"><span>Officials</span><strong>{{ $officials->count() }}</strong></div><div class="pd-stat"><span>Pending claims</span><strong>{{ $claims->where('status', 'pending')->count() }}</strong></div></div>
<div class="pd-cols" style="margin-top:16px"><div class="pd-card"><h3>Recent token activity</h3><div class="pd-list">@forelse($transactions->take(5) as $transaction)<div class="pd-item"><strong>{{ $transaction->candidate->name ?? str($transaction->type)->headline() }}</strong><div class="pd-muted">{{ $transaction->created_at->format('d M Y, H:i') }} &middot; {{ number_format($transaction->amount) }} tokens</div></div>@empty<div class="pd-empty">No token activity yet.</div>@endforelse</div></div><div class="pd-card"><h3>Recent claims</h3><div class="pd-list">@forelse($claims->take(5) as $claim)<div class="pd-item"><strong>{{ $claim->candidate->name ?? 'Aspirant' }}</strong><div class="pd-muted">{{ str($claim->status)->headline() }}</div></div>@empty<div class="pd-empty">No claims submitted.</div>@endforelse</div></div></div>
</section><section class="pd-panel" data-content="aspirants">
<div class="pd-heading"><div><h2>Aspirants</h2><p>Manage aspirants attached to {{ $party->name }}.</p></div><a class="pd-btn" href="{{ route('party.candidates.create') }}"><i class="fas fa-plus"></i>Add Aspirant</a></div>
<div class="pd-card">
<form method="GET" class="pd-form-grid" style="margin-bottom:20px"><input type="hidden" name="section" value="aspirants">
<div class="pd-field"><label for="asp-search">Search</label><input id="asp-search" name="search" value="{{ request('search') }}" placeholder="Aspirant name"></div>
<div class="pd-field"><label for="asp-position">Position</label><select id="asp-position" name="position"><option value="">All positions</option>@foreach($positions as $position)<option value="{{ $position->id }}" @selected(request('position') == $position->id)>{{ $position->name }}</option>@endforeach</select></div>
<div class="pd-field"><label for="asp-status">Approval status</label><select id="asp-status" name="approval_status"><option value="">All statuses</option>@foreach(['pending','approved','rejected'] as $status)<option value="{{ $status }}" @selected(request('approval_status') === $status)>{{ str($status)->headline() }}</option>@endforeach</select></div>
<div class="pd-field" style="align-self:end"><button class="pd-btn" type="submit"><i class="fas fa-filter"></i>Apply filters</button></div></form>
<div class="pd-table-wrap"><table class="pd-table"><thead><tr><th>Aspirant</th><th>Position</th><th>Status</th><th>Tokens</th><th>Action</th></tr></thead><tbody>
@forelse($candidates as $candidate)<tr><td>{{ $candidate->name }}</td><td>{{ $candidate->position->name ?? '-' }}</td><td>{{ str($candidate->approval_status)->headline() }}</td><td>{{ number_format($candidate->tokenWallet->balance ?? 0) }}</td><td><a class="pd-btn secondary" href="{{ route('party.candidates.edit',$candidate) }}">Edit</a></td></tr>@empty<tr><td colspan="5" class="pd-empty">No aspirants match these filters.</td></tr>@endforelse
</tbody></table></div><div class="pd-pagination">{{ $candidates->appends(['section'=>'aspirants'])->links() }}</div></div>
</section>
<section class="pd-panel" data-content="claims">
<div class="pd-heading"><div><h2>Aspirant claims</h2><p>Request association with an existing aspirant profile.</p></div></div>
<div class="pd-cols"><div class="pd-card"><h3>Submit a claim</h3><form method="POST" action="{{ route('party.claims.store') }}" class="pd-form">@csrf<div><x-aspirant-search name="candidate_id" :search-url="route('party.candidates.search', ['context' => 'claim'])" label="Search existing aspirant" placeholder="Type at least 2 characters..." help="Search and select the profile you want this party to claim." empty-text="No claimable aspirants match your search." selection-note="This profile will be submitted for administrator approval." :required="true" /></div><button class="pd-btn" type="submit">Submit claim</button></form></div>
<div class="pd-card"><h3>Claim history</h3><div class="pd-list">@forelse($claims as $claim)<div class="pd-item"><strong>{{ $claim->candidate->name ?? 'Aspirant' }}</strong><div class="pd-muted">{{ str($claim->status)->headline() }}</div></div>@empty<div class="pd-empty">No claims submitted yet.</div>@endforelse</div></div></div>
</section>
<section class="pd-panel" data-content="tokens">
<div class="pd-heading"><div><h2>Party tokens</h2><p>Buy tokens for the party pool and distribute them to approved aspirants.</p></div></div>
<div class="pd-cols"><div class="pd-card"><h3>Distribute tokens</h3><form method="POST" action="{{ route('party.tokens.distribute') }}" class="pd-inline">@csrf<div><x-aspirant-search name="candidate_id" :search-url="route('party.candidates.search', ['context' => 'distribution'])" label="Search approved aspirant" placeholder="Type at least 2 characters..." help="Search approved aspirants currently assigned to this party." empty-text="No approved party aspirants match your search." selection-note="Tokens will be transferred to this aspirant's wallet." :required="true" /></div><div class="pd-field"><label for="token-amount">Amount</label><input id="token-amount" type="number" min="1" name="amount" placeholder="Tokens" required></div><button class="pd-btn" type="submit">Transfer</button></form></div>
<div class="pd-card"><h3>Buy party tokens</h3><div class="pd-list">@forelse($packages as $package)<form method="POST" action="{{ route('party.tokens.purchase') }}" class="pd-item pd-form">@csrf<input type="hidden" name="package_id" value="{{ $package->id }}"><div class="pd-item-row"><strong>{{ $package->name }}</strong><span>{{ number_format($package->token_amount) }} tokens / KES {{ number_format($package->price) }}</span></div><div class="pd-form-grid"><div class="pd-field"><label>Payment phone</label><input name="phone" value="{{ auth()->user()->phone }}" required></div><div class="pd-field"><label>Receipt email</label><input type="email" name="email" value="{{ auth()->user()->email }}" required></div></div><button class="pd-btn" type="submit">Purchase package</button></form>@empty<div class="pd-empty">No token packages available.</div>@endforelse</div></div></div>
</section><section class="pd-panel" data-content="transactions">
<div class="pd-heading"><div><h2>Token transactions</h2><p>Review party purchases and aspirant distributions.</p></div></div>
<div class="pd-cols"><div class="pd-card"><h3>Distributions and ledger</h3><div class="pd-list">@forelse($transactions as $transaction)<div class="pd-item"><strong>{{ $transaction->candidate->name ?? str($transaction->type)->headline() }}</strong><div class="pd-muted">{{ $transaction->created_at->format('d M Y, H:i') }} &middot; {{ number_format($transaction->amount) }} tokens</div></div>@empty<div class="pd-empty">No transactions recorded.</div>@endforelse</div></div>
<div class="pd-card"><h3>Purchase history</h3><div class="pd-list">@forelse($purchases as $purchase)<div class="pd-item"><strong>{{ $purchase->package_name }}</strong><div class="pd-muted">{{ number_format($purchase->token_amount) }} tokens &middot; KES {{ number_format($purchase->price) }} &middot; {{ str($purchase->status)->headline() }}</div></div>@empty<div class="pd-empty">No purchases recorded.</div>@endforelse</div></div></div>
</section>
@if($membership->role === 'party_admin')
<section class="pd-panel" data-content="officials">
<div class="pd-heading"><div><h2>Party officials</h2><p>Manage people who can access this party workspace.</p></div></div>
<div class="pd-cols"><div class="pd-card"><h3>Add an official</h3><form method="POST" action="{{ route('party.officials.store') }}" class="pd-form">@csrf<div class="pd-field"><label for="official-name">Full name</label><input id="official-name" name="name" required></div><div class="pd-field"><label for="official-email">Email</label><input id="official-email" type="email" name="email" required></div><div class="pd-field"><label for="official-password">Temporary password</label><input id="official-password" type="password" name="password" required></div><div class="pd-field"><label for="official-role">Access role</label><select id="official-role" name="role"><option value="party_staff">Party staff</option><option value="party_admin">Party admin</option></select></div><button class="pd-btn" type="submit">Add official</button></form></div>
<div class="pd-card"><h3>Current officials</h3><div class="pd-list">@foreach($officials as $official)<div class="pd-item pd-item-row"><div><strong>{{ $official->name }}</strong><div class="pd-muted">{{ str($official->pivot->role)->headline() }}</div></div>@unless($official->is(auth()->user()))<form method="POST" action="{{ route('party.officials.destroy',$official) }}">@csrf @method('DELETE')<button class="pd-btn danger" type="submit">Remove</button></form>@endunless</div>@endforeach</div></div></div>
</section>
@endif
</div></div></main>
<script>
document.addEventListener('DOMContentLoaded',()=>{const buttons=[...document.querySelectorAll('[data-panel]')];const panels=[...document.querySelectorAll('[data-content]')];const names=buttons.map(button=>button.dataset.panel);const query=new URLSearchParams(location.search).get('section');const hash=location.hash.slice(1);const activate=(requested,historyUpdate=true)=>{const name=names.includes(requested)?requested:'overview';buttons.forEach(button=>{const active=button.dataset.panel===name;button.classList.toggle('active',active);button.setAttribute('aria-current',active?'page':'false')});panels.forEach(panel=>panel.classList.toggle('active',panel.dataset.content===name));if(historyUpdate)history.replaceState(null,'',`${location.pathname}${location.search}#${name}`)};buttons.forEach(button=>button.addEventListener('click',()=>activate(button.dataset.panel)));activate(query||hash||'overview',false)});
</script>
@endsection